language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files

addons:
  apt:
    packages:
    - jq

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

matrix:
    fast_finish: true
    include:
          # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

          # Test the latest stable release
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text --coverage-clover=coverage.clover"
        - php: 8.0

          # Test with Symfony 3
        - php: 7.3
          env: SYMFONY_VERSION="^3"

          # Test with Symfony 4
        - php: 7.3
          env: SYMFONY_VERSION="^4"

          # Test with Symfony 5
        - php: 7.3
          env: SYMFONY_VERSION="^5"

          # Latest commit to master
        - php: 7.3
          env: STABILITY="dev"

          # Upcoming PHP version
        - php: 7.4snapshot

    allow_failures:
          # dev-master is allowed to fail
        - env: STABILITY="dev"
          # Upcoming PHP version is allowed to fail
        - php: 7.4snapshot

before_install:
    - if [ "$COVERAGE" != true ]; then phpenv config-rm xdebug.ini || true; fi
    - if [ -n "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - |
      if [ -n "$SYMFONY_VERSION" ]; then
        for symfony_package in $(jq -r '.require | keys[]' composer.json | grep '^symfony/'); do
          composer require --no-update "${symfony_package}:${SYMFONY_VERSION}"
        done
      fi

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/phpunit ${PHPUNIT_FLAGS}

after_script:
  - |
    if [ "$COVERAGE" = true ] && [ -e coverage.clover ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
